### PR TITLE
fix: remove unnecessary `as_any()` to fix compilation error

### PR DESCRIPTION
**Pull request by Jefffrey**
Merging in https://github.com/apache/datafusion/pull/21031 broke main due to https://github.com/apache/datafusion/pull/21573 landing before it

### CODE REVIEW

**Comment by buraksenn** [comment]
Thanks @Jefffrey I was just checking a failure in my PR and as about to open this

**Review by buraksenn — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
TY @Jefffrey
