### PR TITLE
perf: Convert inner joins to semi joins when equivalent

### LINKED ISSUE #22594: Optimize inner joins to semi joins when possible
### Is your feature request related to a problem or challenge?

We can convert inner joins to semi joins automatically in some cases. For example, we can convert an inner join to a left semi join if

* (1) Nothing above the join uses a column from the RHS of the join, and EITHER 
* (2) (A) The plan above the join is duplicate-insensitive (e.g., `DISTINCT` or some `GROUP BY`s), OR
* (2) (B) We can use functional dependencies to prove that the RHS is unique on the join keys

And symmetrically for inner -> right semi for LHS.

Many of the TPC-DS queries would benefit from this. Plans in 2(A) generally benefit more because we're able to avoid producing duplicate tuples in the first place; 2(B) is a smaller win but still useful.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #22594

## Rationale for this change

This PR extends the `EliminateJoin` rewrite pass to replace inner joins with semi joins in some cases. An inner join `L ⋈ R` can be rewritten to a left semi join `L ⋉ R` if two conditions hold:

1. None of R's columns are referenced above the join
2. (a) each L row matches at most one R row, OR (b) the consumers of the join result are insensitive to duplicates

(And symmetrically with right semi joins.)

## What changes are included in this PR?

* Add `for_each_referenced_index` helper that is used by both `EliminateJoin` and `EliminateProjections`
* Introduce `LiveColumns` type to track the "live" (referenced by parent) columns of a plan node
* Add inner -> semi join rewrite to `EliminateJoin`
* Add unit and SLT tests for rewrite behavior
* Update SLT test fixtures for plan changes

## Are these changes tested?

Yes; new tests added.

## Are there any user-facing changes?

Some plan changes but no behavioral changes.

### CODE REVIEW

**Comment by neilconway** [comment]
run benchmarks tpcds

File: datafusion/optimizer/src/eliminate_join.rs [hunk 1]
```diff
@@ -15,19 +15,75 @@
...
+        Aggregate, Distinct, DistinctOn, EmptyRelation, Filter, Join, Limit, LogicalPlan,
+        Partitioning, Projection, Repartition, Sort, SubqueryAlias,
+    },
 };
+use std::sync::Arc;
+
+/// The columns that are "live" at a plan node, i.e., which of its output
+/// columns are referenced by an ancestor node. Represented as a set of column
+/// indices, relative to the node's schema.
+type LiveColumns = HashSet<usize>;
```
Comment (neilconway) [inline datafusion/optimizer/src/eliminate_join.rs]: 1. This is similar but not identical to the `RequiredIndices` data structure used by `OptimizeProjections`. `RequiredIndices` cares about insertion order but we don't, so it seemed cleaner to use a different data structure here.
2. It would be better to use a bitmap than a `HashSet`. We could do so by adding a dependency on a third-party bitmap implementation (e.g., https://github.com/petgraph/fixedbitset, which one of our indirect dependencies already pulls in). But the performance impact should be small, so I'm not sure it's worth adding the dep.

**Comment by neilconway** [comment]
Digging into some of the TPC-DS query plan changes, we ran into two different planner bugs: #22679 and #22674. This PR will also benefit (on TPC-DS and TPC-H) from landing #22646

**Comment by Dandandan** [comment]
run benchmarks

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by Dandandan** [comment]
@neilconway FYI quite some plans changed now 🚀 

Can you take a look at the PR

**Comment by neilconway** [comment]
run benchmarks

**Comment by neilconway** [comment]
@Dandandan I updated the expected plans; everything that changed seemed inline with the intended goal of this PR.

Looking at the latest benchmark numbers, some of the TPC-DS regressions. The plan was q54 still seems to have regressed; I suspect there's another planner/stats bug here, taking a look now.

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by Dandandan** [comment]
The plans are looking better, although I think we probably need to have some more specialization (semi join? / single key column? etc.) to benefit from it more?

**Comment by alamb** [comment]
As I understand it, the idea of this optimization is to use semi-join which in theory should be more efficient than a normal INNER JOIN. However, it seems the DataFusion semi-join doesn't actually have a noticably faster implementation? 

If so it seems reasonable to me to merge this PR and maybe file a ticket to improve SEMI join performance

**Comment by neilconway** [comment]
@alamb There are two scenarios where this should be a win:

1. Replacing an inner join with a left semi-join, where the inner join would have produced at most one matching row for each left tuple. Exactly the same intermediate result sets, but should be slightly faster due to less join overhead etc (plus it lets the planner place tighter bounds on the size of the join output set). I haven't done detailed microbenchmarks yet, but you're right that it seems we aren't seeing major wins from this and it might merit further investigation.
2. Replacing an inner join with a left semi-join, where each left tuple can match multiple right tuples, but then those duplicates are ignored/filtered out by an upstream operator (e.g., `DISTINCT`). In this scenario, this optimization could be a major performance win, depending on the number of duplicates produced of course.

(Symmetric for right semi joins as well, of course.)

I can't see a scenario where this PR would regress performance.

There were some semi-join planner/stats bugs that resulted in picking worse plans; https://github.com/apache/datafusion/pull/22762 fixes the last one that I know about. Once that lands I'll rerun the benchmarks for this PR.

**Comment by Dandandan** [comment]
> Replacing an inner join with a left semi-join, where the inner join would have produced at most one matching row for each left tuple. Exactly the same intermediate result sets, but should be slightly faster due to less join overhead etc (plus it lets the planner place tighter bounds on the size of the join output set). I haven't done detailed microbenchmarks yet, but you're right that it seems we aren't seeing major wins from this and it might merit further investigation.

I think in this situation there is only limited difference currently, it will use most of the same code paths. There is probably some further specialization we can do for different join types.

**Comment by alamb** [comment]
run benchmark sql_planner

File: datafusion/optimizer/src/eliminate_join.rs [hunk 2]
```diff
@@ -15,19 +15,69 @@
 // specific language governing permissions and limitations
 // under the License.
 
-//! [`EliminateJoin`] rewrites `INNER JOIN` with `true`/`null`
-use crate::optimizer::ApplyOrder;
+//! [`EliminateJoin`] rewrites inner joins to simpler forms to make them cheaper
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:18]: I always enjoy reading PRs where you learn something from the comments ❤️ 🤓

File: datafusion/optimizer/src/eliminate_join.rs [hunk 3]
```diff
@@ -15,19 +15,69 @@
...
+    logical_plan::{
+        Aggregate, Distinct, DistinctOn, EmptyRelation, Filter, Join, Limit, LogicalPlan,
+        Partitioning, Projection, Repartition, Sort, SubqueryAlias,
+    },
 };
+use std::sync::Arc;
+
+/// The columns that are "live" at a plan node, i.e., which of its output
+/// columns are referenced by an ancestor node. Represented as a set of column
+/// indices, relative to the node's schema.
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:76]: it might be useful to refer back to the module level comments that explain this structure in more detail

File: datafusion/optimizer/src/eliminate_join.rs [hunk 4]
```diff
@@ -15,19 +15,69 @@
...
+//!
+//! * An inner join can be rewritten to an empty relation if the join condition
+//!   is trivially false.
+//!
+//! * An inner join `L ⋈ R` can be rewritten to a left semi join `L ⋉ R`
+//!   (`LeftSemi`), which keeps the rows of L that have a match in R and outputs
+//!   only L's columns. The rewrite to `L ⋉ R` is valid when both of the
+//!   following are true:
+//!
+//!     1. None of R's columns are referenced above the join.
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:29]: 👍

File: datafusion/optimizer/src/eliminate_join.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/src/eliminate_join.rs]: You could potentially use arrow BooleanBufferBuilder as a mutable bitset:  https://docs.rs/arrow/latest/arrow/array/struct.BooleanBufferBuilder.html

Not sure if that is actually faster or not

File: datafusion/optimizer/src/eliminate_join.rs [hunk 5]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+        })
+    })
+}
+
+fn rewrite_node(
+    plan: LogicalPlan,
+    live: LiveColumns,
+    duplicate_insensitive: bool,
+) -> Result<Transformed<LogicalPlan>> {
+    match plan {
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:196]: I think this code depends on being able to walk all expressions used in the plan to remain correct. I worry if we ever modify a LogicalPlan node to add a new Expr container -- this code would continue to compile, and we would probably end up with subtle bugs

SOme ideas on how to address:
1. Use this API for visiting expressions/finding live columns: https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.LogicalPlan.html#method.apply_expressions
2. name all fields (remove `..`) so that if any field is added, the PR must also explicitly change this file too

File: datafusion/optimizer/src/eliminate_join.rs [hunk 6]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+        LogicalPlan::Sort(Sort { expr, input, fetch }) => {
+            // Adds the sort-key columns to `live`.
+            let mut child_live = live;
+            extend_live_columns(
+                &mut child_live,
+                expr.iter().map(|s| &s.expr),
+                input.schema(),
+            )?;
+
+            // A `fetch` (top-N) makes the row count observable, so duplicate-
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:296]: I was confused at first as I thought that every sort duplicate insensitive? But now I see now that the sort will preserve its ancestor's insensitivity -- basically sorting before/after dupe removal is equivalent (assuming the sort doesn't have a topk) 👍

File: datafusion/optimizer/src/eliminate_join.rs [hunk 7]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+            (duplicate_insensitive, true)
+        }
+        JoinType::RightSemi | JoinType::RightAnti | JoinType::RightMark => {
+            (true, duplicate_insensitive)
+        }
+        JoinType::Left | JoinType::Right | JoinType::Full => (false, false),
     }
 }
 
+/// Rewrites an inner join to a semi join when the removed side has no
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:480]: Minor: these might be better encapsulated as methods on `LiveColumns`

File: datafusion/optimizer/src/eliminate_join.rs [hunk 8]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+        if *idx < left_len {
+            left.insert(*idx);
+        } else {
+            right.insert(*idx - left_len);
+        }
+    }
+    (left, right)
+}
+
+fn side_unique_on_join<'a>(
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:552]: Woudl this be better / easier to discover / reuse as a method on Join?

File: datafusion/optimizer/src/eliminate_join.rs [hunk 9]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+                .all(|idx| join_key_indices.contains(idx))
+    })
+}
+
+fn all_columns(schema: &DFSchema) -> LiveColumns {
+    (0..schema.fields().len()).collect()
+}
+
+/// The columns of `schema` referenced by any of `exprs`.
+fn live_columns<'a>(
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs]: Could be `LoveColumns::try_new()` potentially, rather than a free function

File: datafusion/optimizer/src/eliminate_join.rs [hunk 10]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+    schema: &DFSchema,
+) -> Result<LiveColumns> {
+    let mut live = LiveColumns::new();
+    extend_live_columns(&mut live, exprs, schema)?;
+    Ok(live)
+}
+
+/// Inserts into `live` the index, within `schema`, of every column referenced
+/// by any of `exprs`.
+fn extend_live_columns<'a>(
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs]: Another good candidate for a `LIveColumns` method perhaps

File: datafusion/sqllogictest/test_files/tpch/plans/q2.slt.part [hunk 11]
```diff
@@ -65,9 +65,9 @@ limit 10;
 logical_plan
 01)Sort: supplier.s_acctbal DESC NULLS FIRST, nation.n_name ASC NULLS LAST, supplier.s_name ASC NULLS LAST, part.p_partkey ASC NULLS LAST, fetch=10
 02)--Projection: supplier.s_acctbal, supplier.s_name, nation.n_name, part.p_partkey, part.p_mfgr, supplier.s_address, supplier.s_phone, supplier.s_comment
-03)----Inner Join: part.p_partkey = __scalar_sq_1.ps_partkey, partsupp.ps_supplycost = __scalar_sq_1.min(partsupp.ps_supplycost)
+03)----LeftSemi Join: part.p_partkey = __scalar_sq_1.ps_partkey, partsupp.ps_supplycost = __scalar_sq_1.min(partsupp.ps_supplycost)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/tpch/plans/q2.slt.part:68]: for anyone else reviewing this, TPCH has FK:PK joins on its schema, so this transformation can potentially help here

File: datafusion/optimizer/src/eliminate_join.rs [hunk 12]
```diff
@@ -42,44 +92,485 @@ impl OptimizerRule for EliminateJoin {
...
+                child_live,
+                child_duplicate_insensitive,
+                |input| {
+                    Ok(LogicalPlan::Aggregate(Aggregate::try_new_with_schema(
+                        input, group_expr, aggr_expr, schema,
+                    )?))
+                },
+            )
+        }
+        LogicalPlan::Distinct(Distinct::All(input)) => {
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_join.rs:254]: I think some of this code is not covered by tests

```shell
cargo llvm-cov --html  test --profile=ci -p datafusion-optimizer
cargo llvm-cov --html  test --profile=ci --test sqllogictests
```

Image

**Review by alamb — APPROVED** [review]
I went through this one carefully, and reviewed the plan changes and code coverage. Looks like a good improvement to me. Thank you @neilconway and @Dandandan 

I think there is one good other than a few more tests

Thanks again

**Comment by Dandandan** [comment]
run benchmarks

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by Dandandan** [comment]
Run benchmark tpcds

**Comment by Dandandan** [comment]
Q14 / Q23 still look like they might be regressing?

File: datafusion/optimizer/src/eliminate_join.rs (hunk 12 above)
Comment (neilconway) [reply datafusion/optimizer/src/eliminate_join.rs:254]: Thanks! I added some more tests.

File: datafusion/optimizer/src/eliminate_join.rs (hunk 9 above)
Comment (neilconway) [reply datafusion/optimizer/src/eliminate_join.rs]: Thanks, good idea! I made `LiveColumns` a proper type with a bunch of methods.

**Comment by neilconway** [comment]
@Dandandan Q23 doesn't result in a plan change and I can't repro that locally; I think that one is just noise.

The regression on Q14 does indeed repro. The plan _should_ strictly be an improvement (just swapping inner joins for semi-joins); it regresses because `RightSemi` joins are actually _slower_ than inner joins in DF right now :) We basically compute an inner join and then do an extra pass to eliminate any duplicates (`get_semi_indices`). Some ideas:

(1) We could pass down a flag indicating that the join is unique on the join keys (case 2a described above), so we can skip the duplicate removal. This _should_ get semi-joins back to parity with inner joins.
(2) Alternatively, we could write a specialized join kernel for semi and anti joins. This has the opportunity to be a significant win, not just get back to parity.

I'm inclined to pursue (2), taking a look at that now.

File: datafusion/optimizer/src/eliminate_join.rs (hunk 8 above)
Comment (neilconway) [reply datafusion/optimizer/src/eliminate_join.rs:552]: I think it would be a bit awkward as a method on `Join`, and I couldn't find other potential callers in the tree right now. But there is probably some opportunity for refactoring some of the logic here, possibly as part of the FunctionalDependencies or DFSchema code. Would prefer to defer to a separate PR though.

File: datafusion/optimizer/src/eliminate_join.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/optimizer/src/eliminate_join.rs]: `BooleanBufferBuilder` would be awkward for what we need (i.e., variably-sized mutable bitmap, iterating over just the set bits, etc.)

Now that `LiveColumns` is a proper type, we can always switch this later. I'm inclined to leave as-is for now, I don't think the performance difference will be large.

**Comment by Dandandan** [comment]
run benchmarks

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by Dandandan** [comment]
run benchmark tpch10

**Comment by alamb** [comment]
For anyone following along, @neilconway and @Dandandan  made Semi-join faster in 
- https://github.com/apache/datafusion/pull/22794

So now we expect this rewrite to be better perofrming 🚀

**Comment by neilconway** [comment]
The latest benchmark numbers look better overall.

Looking at the TPC-H numbers, at least locally w/ SF10, it seems that Q22 improves because switching to a semi-join results in emitting different stats for the join output, and those stats result in avoiding some poor planner choices we made for operators above the semi-join. So while semi-joins are a bit easier to compute stats for than inner joins, the win there is a bit coincidental. Q13 and Q22 are noise (no plan change from this rewrite).

I looked at TPC-DS Q14, it's interesting: locally, the rewrite regresses performance by ~15% with >= 2 partitions but improves performance by ~10% with a single partition. The reason seems to be that using a semi-join results in less flexibility for subsequent partition decision making, so the overall plan performs worse because it needs a repartition that the inner join plan didn't.

I think we're okay to merge this as-is, but there's a bunch of room for further improvements:

1. #22794 reduced semi-join overhead compared to inner joins, but semi-joins are still slower than inner joins in DF. We might still see overall performance improvements from this rewrite -- two causes might be plan changes/improvements, or perhaps because semi-joins effectively do duplicate elimination sooner, which reduces the # of intermediate values passed between operators. But if we had a specialized join kernel for semi-joins I think we could get significantly better performance on the join itself.
4. As mentioned for Q14 above, semi-joins actually have one negative property compared to inner joins: their partitioning behavior is less flexible. Once we commit to LeftSemi vs. RightSemi (which we do on the basis of which join operand is smaller), we never consider swapping back -- even if changing the join orientation would result in better partitioning behavior for downstream operators. That seems like something we could improve, e.g., in `EnsureRequirements`.

**Comment by alamb** [comment]
Given we are cranking on the join implementations this release, let's merge this in.

**Comment by alamb** [comment]
Thanks again @neilconway and @Dandandan

**Comment by alamb** [comment]
Looks like the merge queue has caught a logical conflict

https://github.com/apache/datafusion/actions/runs/27299136079/job/80639801196

```
error[E0004]: non-exhaustive patterns: `&datafusion_expr::Partitioning::Range(_)` not covered
    --> datafusion/optimizer/src/eliminate_join.rs:326:19
     |
 326 |             match &partitioning_scheme {
     |                   ^^^^^^^^^^^^^^^^^^^^ pattern `&datafusion_expr::Partitioning::Range(_)` not covered
     |
note: `datafusion_expr::Partitioning` defined here
    --> datafusion/expr/src/logical_plan/plan.rs:4443:1
     |
4443 | pub enum Partitioning {
     | ^^^^^^^^^^^^^^^^^^^^^
...
4451 |     Range(RangePartitioning),
     |     ----- not covered
     = note: the matched value is of type `&datafusion_expr::Partitioning`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
     |
 330 ~                 Partitioning::RoundRobinBatch(_) => {},
 331 +                 &datafusion_expr::Partitioning::Range(_) => todo!()
     |
```

**Comment by neilconway** [comment]
@alamb Updated, CI should be fixed.
