### PR TITLE
fix: broken main branch due to merge race in #21211

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
## Which issue does this PR close?

Fixes compilation error and SLT test failure on main branch.

## Rationale for this change

PR #21211 (Add output skewness metric) was based on a version before #21160 renamed `MetricType::DEV` to `MetricType::Dev`. When both merged, main broke with a compilation error. Additionally, #21211 changed the `scan_efficiency_ratio` display precision (e.g. `22%` → `22.13%`), causing one SLT test to fail.

## What changes are included in this PR?

1. `MetricType::DEV` → `MetricType::Dev` in `baseline.rs` (compilation fix)
2. Update `explain_analyze.slt` expected output for `scan_efficiency_ratio` precision change

## Are these changes safe?

Yes — fixes compilation error and test expectation, no behavior change.

### CODE REVIEW

**Comment by zhuqi-lucas** [comment]
CI status: `cargo test`, `extended_tests`, and `build test` all pass. The only failure is `sqlite test suite` which reports "query is expected to fail, but actually succeed" — this is a pre-existing issue on main (likely from #21126 fixing duplicate column name support), unrelated to this fix. That requires updating the `datafusion-testing` submodule's expected failure list.

**Comment by zhuqi-lucas** [comment]
Ok, it's duplicated with https://github.com/apache/datafusion/pull/21242
