### PR TITLE
fix: CI build failed on main

### LINKED ISSUE #13639: CI build failed on main
### Describe the bug

> error[E0432]: unresolved import `indexmap`
  --> datafusion/physical-expr/src/equivalence/class.rs:23:5
   |
23 | use indexmap::IndexSet;
   |     ^^^^^^^^ use of undeclared crate or module `indexmap`

Details: https://github.com/apache/datafusion/actions/runs/12151105350/job/33885120868

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #13639.

## Rationale for this change
There is a logical conflict between #13611 and main.
`indexmap::IndexSet` was replaced to `common::IndexSet` in #13611, but there's still code using it on the main.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks for the quick fix @jonahgao 👍

**Comment by jonahgao** [comment]
Thanks @Weijun-H for the review.
