### PR TITLE
Fix build `use of undeclared type ShowStatementFilter`

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Build on main is broken due to a logical conflict between

- https://github.com/apache/datafusion/pull/13799
- https://github.com/apache/datafusion/pull/13767

Example failure:

https://github.com/apache/datafusion/actions/runs/12441590178/job/34738687199
```
error[E0433]: failed to resolve: use of undeclared type `ShowStatementFilter`
    --> datafusion/sql/src/statement.rs:2003:17
     |
2003 |                 ShowStatementFilter::Like(like) => {
     |                 ^^^^^^^^^^^^^^^^^^^ use of undeclared type `ShowStatementFilter`
     |
help: a struct with a similar name exists
     |
2003 |                 ShowStatementIn::Like(like) => {
     |                 ~~~~~~~~~~~~~~~
help: consider importing one of these enums
     |
18   + use crate::statement::ast::ShowStatementFilter;
     |
18   + use sqlparser::ast::ShowStatementFilter;
     |

    Checking datafusion-functions v43.0.0 (/__w/datafusion/datafusion/datafusion/functions)
    Checking datafusion-physical-plan v43.0.0 (/__w/datafusion/datafusion/datafusion/physical-plan)
    Checking datafusion-functions-aggregate v43.0.0 (/__w/datafusion/datafusion/datafusion/functions-aggregate)
Some errors have detailed explanations: E0[412](https://github.com/apache/datafusion/actions/runs/12441590178/job/34738687199#step:6:413), E0433.
```

## What changes are included in this PR?

Fix logical conflict

### CODE REVIEW

**Review by goldmedal — APPROVED** [review]
Thanks @alamb for fixing it 👍
