### ISSUE TITLE
[EPIC] Attach `Diagnostic` to more errors

### ISSUE THREAD

**Issue by eliaperantoni** [apache/datafusion#14429]
### Is your feature request related to a problem or challenge?

In #13664 we introduced the `Diagnostic` type and `DataFusionError::Diagnostic`. They allow enriching errors with messages meant for consumption by end users of an application built on top of DataFusion, by providing rich information and context that directly references locations in the SQL query. They enable features like:

![](https://github.com/user-attachments/assets/32efeb4f-aad9-41c9-a1e3-600a00d525c3)

See `datafusion/sql/tests/cases/diagnostic` for examples on how to extract and use diagnostics:

https://github.com/apache/datafusion/blob/d5428b21d6486e5b7db525d314ee9119a512c397/datafusion/sql/tests/cases/diagnostic.rs#L132-L140

In that PR, we only implemented diagnostics for:

- Unresolved table references
- Unresolved column references (qualified and non)
- Non-aggregate expressions missing from `GROUP BY` clause
- Ambiguous column references
- Wrong number of columns in set expression (e.g. `UNION`)
- Incompatible types in binary expressions

This issue is about using `Diagnostic` in more places, and adding related tests to `datafusion/sql/tests/cases/diagnostic`. We think we should at least implement the following, but suggestions are welcome and encouraged:

TODO

### Describe the solution you'd like

The implementation should follow the steps of #13664, by calling `DataFusionError.with_diagnostic` to attach a `Diagnostic` to an error that is currently being returned. Tests should be added to `datafusion/sql/tests/cases/diagnostic` for each newly supported scenario.

For some of these items, it might be necessary to enrich the logical types with the `Span` information coming from the parser. This should be done using the `datafusion::common::Spans` type (note the "s"), introduced in #13664 to add span information to `datafusion::common::Column`.

It is desirable that the implementation is as little invasive as possible, in that it shouldn't require changing tons of function calls and types, unless absolutely necessary. The public facing API shouldn't change. The `Diagnostic` should be attached as soon as possible to the creation of the wrapped `DataFusionError` (i.e. deep in the call stack) and every error should ideally have just one `Diagnostic`.

**Comment by jsai28** [comment]
Hi, is this still a potential GSoC project? It looks like many of the tickets in this epic have an open pull request and are close to completion. If you know of any other areas that could use some DX improvements, I'd be interested to work on them!

**Comment by eliaperantoni** [comment]
Hey @jsai28! You're right, most of them are being worked on. But just recently I've filed #15276. I was planning on doing it myself but you could take it you'd like :) In that case, let's coordinate on the implementation details 😊

**Comment by jsai28** [comment]
@eliaperantoni Sure, I'll take a look at that! Thanks

**Comment by alamb** [comment]
Are there any updates on this EPIC? Are we still working on it?

**Comment by eliaperantoni** [comment]
> Are there any updates on this EPIC? Are we still working on it?

On my side, unfortunately I no longer have the time to follow the updates on these tickets, or provide guidance, at the moment :/

**Comment by buraksenn** [comment]
I've opened a PR for one issue part of this epic. @eliaperantoni if you've no time I can try to lead this epic and resolve issues.

**Comment by eliaperantoni** [comment]
@buraksenn Absolutely! Feel free to take over this epic :)
