### PR TITLE
fix: use datafusion_expr instead of datafusion crate

### PR DESCRIPTION
**Pull request by hsiang-c**
## Which issue does this PR close?

- N/A

## Rationale for this change

 - Building the `datafusion-spark` crate in isolation, e.g. `cargo clippy -p datafusion-spark` fails as indicated by https://github.com/apache/datafusion/pull/21043
 
```Shell
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `datafusion`
  --> datafusion/spark/src/function/string/is_valid_utf8.rs:19:5
   |
19 | use datafusion::logical_expr::{ColumnarValue, Signature, Volatility};
   |     ^^^^^^^^^^ use of unresolved module or unlinked crate `datafusion`
```

## What changes are included in this PR?

Fix import statement. No code changes.

## Are these changes tested?

Yes, building `datafusion-spark` crate works now.

## Are there any user-facing changes?

N/A

### CODE REVIEW

**Review by Jefffrey — APPROVED** [review]

**Comment by Jefffrey** [comment]
Thanks @hsiang-c
