### PR TITLE
Fix build with missing `use` ( `" return internal_err!("UDF returned a different ..."`)

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

It appears https://github.com/apache/datafusion/pull/10277 had a logical conflict

https://github.com/apache/datafusion/actions/runs/8899641374/job/24439454308

```
error: cannot find macro `internal_err` in this scope
   --> datafusion/physical-expr/src/scalar_function.rs:156:32
    |
156 |                         return internal_err!("UDF returned a different number of rows than expected. Expected: {}, Got: {}", 
    |                                ^^^^^^^^^^^^
    |
help: consider importing this macro
    |
32  + use datafusion_common::internal_err;
```

## Rationale for this change

Fix build

## What changes are included in this PR?
Add required `use`

## Are these changes tested?
CI

### CODE REVIEW

**Review by comphead — APPROVED** [review]
nice catch @alamb

**Comment by alamb** [comment]
Thanks @comphead
