### PR TITLE
feat: Use Cached Metadata for ListingTable Statistics

### PR DESCRIPTION
**Pull request by shehabgamin**
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/17002

## Rationale for this change

Faster queries and downstream usability.

## What changes are included in this PR?

1. Make Parquet reader public so downstream crates can use it.
2. Use cached metadata for ListingTable statistics for faster queries.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by shehabgamin** [comment]
EDIT:
I had collect_statistics turned off when doing this, so disregard the results. Striking out the results below to not cause confusion.

~~Not seeing any benefit when testing with S3 data cc @alamb~~

> 
> ~~Tested on Derived TPC-H (100 GB) querying S3 from EC2.~~
> 
> ~~EC2 Tab 1:~~
> 
> 
> ~~`env RUSTFLAGS="-C target-cpu=native" cargo build -r -p sail-cli --bins --target-dir target/parquet-metadata-cache`~~
> 
> ~~`env \
> RUST_LOG=info \
> SAIL_PARQUET__FILE_METADATA_CACHE=true \
> target/parquet-metadata-cache/release/sail spark server`~~
> 
> 
> ~~EC2 Tab 2:~~
> 
> 
> ~~`python python/pysail/examples/spark/tpch.py \
> --data-path s3://BUCKET-PATH HERE \
> --query-path python/pysail/data/tpch/queries \
> --query-all \
> --num-runs 3`~~
> 
> ~~Run 1 Total time for all queries: 180.1174988746643 seconds.
> Run 2 Total time for all queries: 184.3733410835266 seconds.
> Run 3 Total time for all queries: 176.67709589004517 seconds.~~

**Comment by shehabgamin** [comment]
EDIT:
I had `collect_statistics` turned off when doing this, so disregard the results. Striking out the results below to not cause confusion.

~~Retesting after: https://github.com/apache/datafusion/pull/17022/commits/c20b142b0672192f7490376d731661e7ffd09d82
and https://github.com/lakehq/sail/pull/687/commits/5580d8bc7cef84f5013dcf50f6a8e7c7f607f8fe as well~~

~~Will update this message when testing done~~

~UPDATE:~
~~`
We can try with both "10G" set and also with nothing set and see.
env \
RUST_LOG=info \
SAIL_PARQUET__FILE_METADATA_CACHE=true \
SAIL_PARQUET__FILE_METADATA_CACHE_LIMIT="10G" \
target/parquet-metadata-cache/release/sail spark server
`~~

~~`python python/pysail/examples/spark/tpch.py \
--data-path s3://PATH \
--query-path python/pysail/data/tpch/queries \
--query-all \
--num-runs 5`~~


~~Run 1 Total time for all queries: 203.74799275398254 seconds.
Run 2 Total time for all queries: 184.0539104938507 seconds.
Run 3 Total time for all queries: 178.30218935012817 seconds.
Run 4 Total time for all queries: 172.49501848220825 seconds.
Run 5 Total time for all queries: 174.7171494960785 seconds.~~

~~`env \
RUST_LOG=info \
SAIL_PARQUET__FILE_METADATA_CACHE=true \
target/parquet-metadata-cache/release/sail spark server`~~


~~`python python/pysail/examples/spark/tpch.py \
--data-path s3://PATH \
--query-path python/pysail/data/tpch/queries \
--query-all \
--num-runs 5`~~


~~Run 1 Total time for all queries: 182.70136904716492 seconds.
Run 2 Total time for all queries: 192.44108653068542 seconds.
Run 3 Total time for all queries: 175.50793719291687 seconds.
Run 4 Total time for all queries: 175.66266465187073 seconds.
Run 5 Total time for all queries: 175.70708632469177 seconds.~~

**Comment by alamb** [comment]
Very exciting -- I have planned time this week to help review and get these various caching things completed

**Review by alamb — COMMENTED** [review]
Thanks @shehabgamin -- the code in this PR looks great. I think we just need to add some tests to make sure we don't break this feature in the future

Maybe we can add a test based on the existing ones that shows a second retrieval of statistics doesn't refetch the same footer 🤔

**Comment by shehabgamin** [comment]
> Thanks @shehabgamin -- the code in this PR looks great. I think we just need to add some tests to make sure we don't break this feature in the future
> 
> 
> 
> Maybe we can add a test based on the existing ones that shows a second retrieval of statistics doesn't refetch the same footer 🤔 
> 
> 
> 
> 

Forsure! Will knock that out when I have some downtime today/tonight

**Comment by shehabgamin** [comment]
> > Thanks @shehabgamin -- the code in this PR looks great. I think we just need to add some tests to make sure we don't break this feature in the future
> > Maybe we can add a test based on the existing ones that shows a second retrieval of statistics doesn't refetch the same footer 🤔
> 
> Forsure! Will knock that out when I have some downtime today/tonight

@alamb Done!

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 1]
```diff
@@ -376,41 +391,123 @@ mod tests {
...
+            Some(9),
+            None,
+            true,
+            ctx.runtime_env().cache_manager.get_file_metadata_cache(),
+        )
+        .await
+        .expect("error reading metadata with hint");
+        assert_eq!(store.request_count(), 4);
+
+        // Increase by 2  because `cache_metadata` is false
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/parquet.rs]: 👍

File: datafusion/datasource-parquet/src/mod.rs [hunk 2]
```diff
@@ -24,7 +24,7 @@ pub mod file_format;
 mod metrics;
 mod opener;
 mod page_filter;
-mod reader;
+pub mod reader;
```
Comment (alamb) [inline datafusion/datasource-parquet/src/mod.rs]: why does this need to be made pub? I reverted the change and things still seem to compile just fine

File: datafusion/datasource-parquet/src/reader.rs [hunk 3]
```diff
@@ -212,7 +212,7 @@ impl ParquetFileReaderFactory for CachedParquetFileReaderFactory {
 /// Implements [`AsyncFileReader`] for a Parquet file in object storage. Reads the file metadata
 /// from the [`FileMetadataCache`], if available, otherwise reads it directly from the file and then
 /// updates the cache.
-pub(crate) struct CachedParquetFileReader {
+pub struct CachedParquetFileReader {
```
Comment (alamb) [inline datafusion/datasource-parquet/src/reader.rs:215]: Likewise, I locally reverted these changes to visibility and everything seems to have compiled just fine

File: datafusion/datasource-parquet/src/file_format.rs [hunk 4]
```diff
@@ -285,6 +286,11 @@ impl ParquetFormat {
         self.options.global.coerce_int96 = time_unit;
         self
     }
+
+    pub fn with_cache_metadata(mut self, cache_metadata: bool) -> Self {
```
Comment (alamb) [inline datafusion/datasource-parquet/src/file_format.rs]: I think this option was removed in https://github.com/apache/datafusion/pull/17062 so it is no longer needed

**Review by alamb — COMMENTED** [review]
Thanks @shehabgamin  -- this code and tests look great to me

I also tried it locally and it is 👨‍🍳 👌 . Note that the count(*) which is based on statistics returns immediately:

```sql
andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion$ ./target/release/datafusion-cli
DataFusion CLI v49.0.0
> create external table hits stored as parquet location 's3://clickhouse-public-datasets/hits_compatible/athena_partitioned/';
0 row(s) fetched.
Elapsed 3.298 seconds.

> select min("WatchID"), max("WatchID") from hits;
+---------------------+---------------------+
| min(hits.WatchID)   | max(hits.WatchID)   |
+---------------------+---------------------+
| 4611686071420045196 | 9223372033328793741 |
+---------------------+---------------------+
1 row(s) fetched.
Elapsed 0.273 seconds.

> select min("WatchID"), max("WatchID") from hits;
+---------------------+---------------------+
| min(hits.WatchID)   | max(hits.WatchID)   |
+---------------------+---------------------+
| 4611686071420045196 | 9223372033328793741 |
+---------------------+---------------------+
1 row(s) fetched.
Elapsed 0.241 seconds.
```

DataFusion 49.0.0:

```
andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion$ ~/Software/datafusion-cli/datafusion-cli-49.0.0
DataFusion CLI v49.0.0
> create external table hits stored as parquet location 's3://clickhouse-public-datasets/hits_compatible/athena_partitioned/';
0 row(s) fetched.
Elapsed 3.313 seconds.

> select min("WatchID"), max("WatchID") from hits;
+---------------------+---------------------+
| min(hits.WatchID)   | max(hits.WatchID)   |
+---------------------+---------------------+
| 4611686071420045196 | 9223372033328793741 |
+---------------------+---------------------+
1 row(s) fetched.
Elapsed 1.380 seconds.
```

However, I tried merging up from main locally and this PR didn't compile. It seems to have a logical conflict with  https://github.com/apache/datafusion/pull/17062

The good news is that since we have removed that field I think this PR can get significantly simpler. Sorry I can't push the changes directly to this PR but I don't have write access to the `lakehq` fork

```
error[E0609]: no field `cache_metadata` on type `datafusion_common::config::ParquetOptions`
   --> datafusion/core/src/datasource/file_format/parquet.rs:204:37
    |
204 |             format.options().global.cache_metadata,
    |                                     ^^^^^^^^^^^^^^ unknown field
```

**Comment by alamb** [comment]
@nuno-faria and @jonathanc-n -- do you have time to review this PR as well?

**Comment by jonathanc-n** [comment]
Some changes might be needed after the removal of `cache_metadata` in #17062, should be small, we just no longer need to do the if check on cache metadata

File: datafusion/datasource-parquet/src/mod.rs (hunk 2 above)
Comment (shehabgamin) [reply datafusion/datasource-parquet/src/mod.rs]: So downstream crates can use it. The reader file looked like it could generally be useful for downstream crates which is why I made the entire reader public.

Currently in Sail we build our own cache for each cache type in `CacheManagerConfig`. I was unable to access `CachedParquetMetaData` to do something like the following unless I made `CachedParquetMetaData` public ([full code](https://github.com/lakehq/sail/pull/687/files#diff-6bdfe8a2d91d5871364cdfb1cba0ae7138850b71d6a164e8daa1f774ca8e1c50)):
```
if let Some(parquet_metadata) =
    value.1.as_any().downcast_ref::<CachedParquetMetaData>()
{
    parquet_metadata
        .parquet_metadata()
        .memory_size()
        .min(u32::MAX as usize)
} 
```

File: datafusion/datasource-parquet/src/reader.rs (hunk 3 above)
Comment (shehabgamin) [reply datafusion/datasource-parquet/src/reader.rs:215]: Same reason as here:
https://github.com/apache/datafusion/pull/17022/files#r2262208618

File: datafusion/core/tests/parquet/page_pruning.rs [hunk 5]
```diff
@@ -903,8 +903,8 @@ async fn without_pushdown_filter() {
     )
     .unwrap();
 
-    // Same amount of bytes are scanned when defaulting to cache parquet metadata
```
Comment (shehabgamin) [inline datafusion/core/tests/parquet/page_pruning.rs:906]: The changes in this PR impacted this test.

Previous discussion:
https://github.com/apache/datafusion/pull/17062/files#r2259644955

cc @alamb @nuno-faria @jonathanc-n

File: datafusion/datasource-parquet/src/file_format.rs [hunk 6]
```diff
@@ -968,19 +973,41 @@ pub async fn fetch_parquet_metadata(
...
+            .await
+            .map_err(DataFusionError::from)?,
+    );
+
+    if let Some(cache) = file_metadata_cache {
+        cache.put(
+            meta,
+            Arc::new(CachedParquetMetaData::new(Arc::clone(&metadata))),
+        );
+    }
```
Comment (nuno-faria) [inline datafusion/datasource-parquet/src/file_format.rs]: I think there is an issue with the `fetch_parquet_metadata` function. When this function is initially called to retrieve the schema (in `fetch_schema`), it will read the metadata and update the cache. When the `CachedParquetFileReader` tries to get the metadata, it checks that it is present in the cache. However, the cached metadata does not contain the page index, as it is not retrieved in the `fetch_parquet_metadata`, meaning it will have to be read in every query.

So this `fetch_parquet_metadata` needs to retrieve the entire metadata for the caching to be effective. On the other hand, after this we will have two different places where the entire metadata is read and cached (`CachedParquetFileReader` and `fetch_parquet_metadata`), so creating an utility function `retrieve_full_parquet_metadata -> Arc<ParquetMetaData>` might be useful to avoid duplicate modifications in the future.

File: datafusion/core/tests/parquet/page_pruning.rs (hunk 5 above)
Comment (nuno-faria) [reply datafusion/core/tests/parquet/page_pruning.rs:906]: I think the page index is not being cached, see https://github.com/apache/datafusion/pull/17022/files#r2262530221.

File: datafusion/datasource-parquet/src/mod.rs (hunk 2 above)
Comment (alamb) [reply datafusion/datasource-parquet/src/mod.rs]: I see -- my concern is that this change might be easy to accidentally undo / break in the future. Maybe to make it more deliberate, you could leave `mod reader` and then `pub use` both `CachedParquetMetaData` and `CachedParquetMetaData` 🤔

File: datafusion/core/tests/parquet/page_pruning.rs (hunk 5 above)
Comment (alamb) [reply datafusion/core/tests/parquet/page_pruning.rs:906]: I was thinking of how we could more easily figure this kind of thing out, and I have a proposal here
- https://github.com/apache/datafusion/issues/17091

File: datafusion/datasource-parquet/src/mod.rs (hunk 2 above)
Comment (shehabgamin) [reply datafusion/datasource-parquet/src/mod.rs]: Works with me!

File: datafusion/datasource-parquet/src/file_format.rs (hunk 6 above)
Comment (shehabgamin) [reply datafusion/datasource-parquet/src/file_format.rs]: Ahh nice catch, will do!

File: datafusion/core/tests/parquet/page_pruning.rs (hunk 5 above)
Comment (shehabgamin) [reply datafusion/core/tests/parquet/page_pruning.rs:906]: Page index not being cached was the issue!

File: datafusion/datasource-parquet/src/file_format.rs [hunk 7]
```diff
@@ -1033,24 +1038,62 @@ impl MetadataFetch for ObjectStoreFetch<'_> {
 /// through [`ParquetFileReaderFactory`].
 ///
 /// [`ParquetFileReaderFactory`]: crate::ParquetFileReaderFactory
-pub async fn fetch_parquet_metadata(
-    store: &dyn ObjectStore,
-    meta: &ObjectMeta,
+pub async fn fetch_parquet_metadata<F: MetadataFetch>(
```
Comment (nuno-faria) [inline datafusion/datasource-parquet/src/file_format.rs:1041]: I wonder now if this function should go to a separate module (a `utils.rs` or similar?). This is because the `file_format` refers to `reader` and `reader` refers to `file_format`. cc @alamb

**Review by nuno-faria — APPROVED** [review]
Thanks @shehabgamin, overall lgmt.

**Comment by alamb** [comment]
```
> create external table hits stored as parquet location 's3://clickhouse-public-datasets/hits_compatible/athena_partitioned/';
0 row(s) fetched.
Elapsed 3.539 seconds.

> select min("WatchID"), max("WatchID") from hits;
+---------------------+---------------------+
| min(hits.WatchID)   | max(hits.WatchID)   |
+---------------------+---------------------+
| 4611686071420045196 | 9223372033328793741 |
+---------------------+---------------------+
1 row(s) fetched.
Elapsed 0.164 seconds.
```

The 0.16 seconds is pretty sweet!


On main, the same query takes 1.3sec
```sql
> select min("WatchID"), max("WatchID") from hits;
+---------------------+---------------------+
| min(hits.WatchID)   | max(hits.WatchID)   |
+---------------------+---------------------+
| 4611686071420045196 | 9223372033328793741 |
+---------------------+---------------------+
1 row(s) fetched.
Elapsed 1.317 seconds.
```

File: datafusion/datasource-parquet/src/file_format.rs (hunk 7 above)
Comment (alamb) [reply datafusion/datasource-parquet/src/file_format.rs:1041]: I agree -- -- I am thinking the code that handles fetching metadata and schema is also getting enough options that it can probably be its own file / structure too. Maybe something like

```rust
pub struct ParquetMetadataFetcher {
...
}
```

So we could use it like

```rust
let fetcher = ParquetMetadataFetcher::new(object_store, path) 
  .with_hint(...);

fetcher.fetch_metadata().await?
```

🤔

File: datafusion/datasource-parquet/src/file_format.rs [hunk 8]
```diff
@@ -312,6 +313,7 @@ async fn fetch_schema_with_location(
     file: &ObjectMeta,
     metadata_size_hint: Option<usize>,
     coerce_int96: Option<TimeUnit>,
+    file_metadata_cache: Option<Arc<dyn FileMetadataCache>>,
```
Comment (alamb) [inline datafusion/datasource-parquet/src/file_format.rs:316]: I re-reviewed these changes and since I think we always now have a file_metadata_cache we could probably make this be non optional. However, there are many tests that need to change

File: datafusion/datasource-parquet/src/file_format.rs (hunk 7 above)
Comment (alamb) [reply datafusion/datasource-parquet/src/file_format.rs:1041]: The more I looked the more it seemed like what would be helpful would be a whole new module `statistics.rs` or something

Comment (alamb) [reply datafusion/datasource-parquet/src/file_format.rs:1041]: I am hacking up a prototype of what this might look like

Comment (alamb) [reply datafusion/datasource-parquet/src/file_format.rs:1041]: I bashed out a PR that pulled the metadata handling out into its own module and I think it looks quite a big nicer. Thank you for the suggestion @nuno-faria 
- https://github.com/apache/datafusion/pull/17127
