### ISSUE TITLE
`swap_hash_join` is no longer public so comet doesn't compile

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13898]
### Describe the bug

- part of to #13835 

When upgrading comet to use the latest datafusion pun (https://github.com/andygrove/datafusion-comet/pull/1) it fails to compile with the following error:

```
error[E0603]: function `swap_hash_join` is private
   --> core/src/execution/planner.rs:56:41
    |
56  |     physical_optimizer::join_selection::swap_hash_join,
    |                                         ^^^^^^^^^^^^^^ private function
    |
note: the function `swap_hash_join` is defined here
   --> /Users/andrewlamb/.cargo/git/checkouts/datafusion-c36d6291a88e48f3/e99e02b/datafusion/core/src/physical_optimizer/join_selection.rs:179:1
    |
179 | / pub(crate) fn swap_hash_join(
180 | |     hash_join: &HashJoinExec,
181 | |     partition_mode: PartitionMode,
182 | | ) -> Result<Arc<dyn ExecutionPlan>> {
    | |___________________________________^
```

This appears to have been introduced in https://github.com/apache/datafusion/pull/13893 from @berkaysynnada 

### To Reproduce

See https://github.com/andygrove/datafusion-comet/pull/1
