### ISSUE TITLE
CI compilation failed: cannot find value `default_nullability` in this scope

### ISSUE THREAD

**Issue by jonahgao** [apache/datafusion#10682]
### Describe the bug

There's a merge conflict with #10640.

### To Reproduce

```sh
error[E0425]: cannot find value `default_nullability` in this scope
    --> datafusion/substrait/src/logical_plan/producer.rs:1414:38
     |
1414 |                         nullability: default_nullability,
     |                                      ^^^^^^^^^^^^^^^^^^^ not found in this scope
```
